#!/bin/bash
# =========================
# AUTHOR: Iarom Madden
# asurf ALIASES/SHORTCUTS/FUNCTIONS
# 	- Aliases as temporary/hacky implementation of autocomp
# ============================
msurf="msurf" # moving tool name
wsurf="wsurf" #
alias dsm.all='$msurf sd.all'
alias dsm.syc='$msurf sy'
alias dsm.sdtr='$msurf sd transfer'
## annotations
#alias gimpn='$wsurf gimp'
#alias srfngl='$wsurf'
#alias anot='flameshot gui'

