#!/bin/env bash

# iarom mail@iarom.org
# centralised calling of asurf tools

[ -n "$1" ] && { cmd="$1"; shift 1; } || cmd="a"

case $cmd in
    m) msurf $@ ;;
    b) msurf "all" ;;
    w) wsurf $@ ;;
    a) wsurf "a";;
    *) nnn ;;
esac
