#!/bin/sh

# #################################
# AUTHOR: IAROM MADDEN future@iarom.org
# Centralise calling of project tools
# #################################

# init

[ -n "$1" ] && { cmd="$1"; shift 1; } || cmd="a"


# cmd #############################

case $cmd in
  m) msurf $@ ;;
  b) msurf "all" ;;
  w) wsurf $@ ;;
  a) wsurf "a";;
  *) nnn ;;
esac

