#!/bin/env bash
# iarom mail@iarom.org

# file processing
# retrieving from sd. moving and sorting files into session and client dirs
# distributing via rclone 2 cloud

# functions
# cp: sd/dcim -> wspace
# rc: wsapce -> cloud
# sd detection
# batch moves
# post move syncs/hooks
# auto sorting dirs; date; file size
# push to remotes; distribution

# init cfg

# TASK set personal configs via external file (migrate to python and use a config modulde...)

_ini()
{
    # loaded via config file
    declare -g rx # root work tree
    declare -g ry    # all years / trees
    declare -g dst_i_def
    declare -g rgx_sdx
    declare -g sd_srt_patterns
    declare -g sdx_mntx
    declare -g sd_bkp_suffix
    declare -g rep_o1_x
    declare -g rep_o1_y
    declare -g rep_g1_x
    declare -g rep_dv_b

    source "${XDG_CONFIG_HOME}/asurf/env"

    # set later
    declare -g psep=""
    declare -g prefix="MS"
    declare -g rgx_sd="${rgx_sdx}"
    declare -g sd_mnt="${sdx_mntx}"

    declare -g sd_i=""    # sd path as arg
    declare -g sd_m=""    # sd path auto matched
    declare -g sd_r=""    # sd root as final sd var
    declare -g sd_dcim="" # dcim
    declare -g sd_bkp=""

    declare -g r="$(realpath "${rx}")" # root work tree
    declare -g dst_i=""                # inputed sub dir
    declare -g dst=""                  # dst full path
}

_prn_l()     { printf "${prefix}:%s\n" " "; }

_prn_c()     { printf "%s\n" "${1}"; }

_prn_b()     { printf "${prefix}: %s\n" "${@}" ; }

_prn_h()
{
    printf "${prefix}: %s\n" \
        "${psep}" \
        "# ${1}" \
        "${psep}"
}

_prn_h2()
{
    printf "${prefix}: %s\n" \
        "${psep}" \
        "# ${1}"
}

_exit1()
{
    _prn_b "exiting (code: 1)"
    exit 1
}

_a2b()
{
    [ -n "${2}" ] || return 0
    eval "${2}"="${!1}"
}

_find_d_grp()
{
    find "${1}" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        -regextype posix-extended \
        -regex ".*${2}" \
        -exec realpath {} \;
            #| grep -E "${2}"
}

_find_d()
{
    find "${1}" -mindepth 1 -maxdepth 1 -type d -exec realpath {} \;
}

# mv

_rs()         { rsync -avP "$1" "$2"; }

_rc_syc()
{
    rclone sync \
        -vP \
        --track-renames \
        --create-empty-src-dirs \
        "${syc_src}" \
        "${syc_dst}"
}

_mv_loop()
{
    while IFS= read -r line
    do
        _prn_b "${line} -> ${2}/*"
        mv "${line}" "${2}/"
    done <<< "${1}"
}

# test

_tst_dir()
{
    eval m="${!1}"
    echo $m
    exit
    _prn_b "checking if dir [ $(eval ${!1}) ] exists"
    if [ -d "${!1}" ]
    then
        return 0
    else
        _prn_b "failed to match dir [ ${1} ]; return 1"
        return 1
    fi
    [ $? -eq 1 ] && return 1
    _a2b "$1" "$2" 
    _prn_b "$1 match -> ${2} = ${!2}"
}

# sd

_set_sd_m()
{
    sd_m=$(_find_d_grp "${sd_mnt}/" "${rgx_sd}") # '../' required
}

_set_sd_i()
{
    [ -n "${sd_i}" ] || return 1
    sd_i="$(realpath "${HOME}/${sd_i}")"
}

_sd_r_i()
{
    [ -d "${sd_r}" ] && return 1
    _set_sd_i
    _tst_dir sd_i sd_r
    [ $? -eq 1 ] \
        || _prn_b "sd root has been set as the input arg"
}

_sd_r_m()
{
    [ -d "${sd_r}" ] && return 1
    _prn_l
    _set_sd_m
    _tst_dir sd_m sd_r
    [ $? -eq 1 ] \
        || _prn_b "sd root has been set by regx"
}

_sd_set_dcim_x()
{
    [ -d "${sd_r}" ] || return 1
    sd_dcim="${sd_r}/DCIM/" 
}

# init asynchronous

_sd_ini_imp()
{
    if [ -z "${dst_i}" ]
    then
        dst="$(realpath "${r}/${dst_i_def}")"
    else
        dst="$(realpath "${r}/${dst_i}")"
    fi
}

_sd_ini()
{
    # test sd existsl; set dcim loc
    #[ -d "$sd_dcim" ] && return # TODO: func which returns parent func?
    sd_i=${1}
    dst_i=${2}
    _sd_ini_imp
    _sd_r_i
    _sd_r_m
    _sd_set_dcim_x
    [ -d "${sd_dcim}" ] || _exit1
}

_sd_prn()
{
    _sd_ini "${@}"
    _prn_l
    _prn_b "sd fed as input: ${sd_i}"
    _prn_b "sd regex matched: ${sd_m}"
    _prn_b "dcim set: ${sd_dcim}"
}

# sd_mv

_sd_rs()   { _rs "${sd_dcim}/" "${dst}"; }
   
_sd_bkp_ini()
{
    sd_bkp_src="$(_find_d "${sd_dcim}")"
    mkdir -p ${sd_bkp:="${sd_r}/${sd_bkp_suffix}"}
    _prn_h "sd bkp"
}

_sd_bkp()
{
    [ -d "${sd_dcim}" ] || _sd_ini
    _sd_bkp_ini
    _mv_loop "${sd_bkp_src}" "${sd_bkp}"
}

_sd_mvx ()
{
    _sd_ini "${@}"
    _sd_rs
    _sd_bkp
}

# srt: date and dirnames
# todo: read input for appending to dirname
# todo: pre-shorted unique id's using anotr method
# todo: use loop functions here that are defined above:
# todo: 80% done
# - currently will become messy if there already exists meta files within the src directory.
# - fine if using clean sd imports
# - required functionality: to base the date on the video file, and move all other associated files with identical identifier with that file.. Future project.

# init and meta data


_prn_h_srt()    { _prn_h "init sorting of dir [ ${src_srt} ]"; }

_prn_b_srt()    { _prn_b "sorting file [ ${src_srt_i} ]"; }

_prn_srt_r()    { _prn_b "dirname suffix?"; }

_srt_date_ini() { src_srt="${1}"; _prn_h_srt; }

_srt_date_read()
{
    _prn_srt_r
    read -r srt_sfx
}

_date_x()
{
    date --date="${1}" +%m%d%a |\
        awk '{print tolower($0)}' |\
        sed 's/.$//'
}

# srt: date/dnames: moving individual files

_srt_date_ini_x ()
{
    [ -f "${1}" ] || return 1
    f=${1}
    di="$(date -r "${f}" "+%D")"
    dh="$(date -r "${f}" "+%H")"

    if [ "${dh}" -lt 12 ]
    then
        xm="a"
    else
        xm="p" # am or pm
    fi

    dst_srt_date=$(_date_x "${di}")
}

_srt_date_ini_y()
{
    sbase=$(dirname "$f" | xargs dirname)
    sdirx="${dst_srt_date}${xm}-${srt_sfx}"
    sdir="${sbase}/${sdirx}"
    dst_srt="${sdir}/$(basename "${f}")"
}

_srt_date_mv_x()
{
    _prn_b "${f} -> ${dst_srt}"
    mkdir -p "${sdir}"
    mv "${f}" "${dst_srt}"
}

_srt_date_mv()
{
    _srt_date_ini_x "${1}"
    _srt_date_ini_y
    _srt_date_mv_x
}

# srt: src dir x containing files to be sorted

_srt_date_ini_i()
{
    src_srt_i="${1}"
    _prn_b_srt
}

_srt_date_ls()
{
    find "${src_srt_i}" -mindepth 1 -maxdepth 1 -type f -exec realpath {} \;
}

_srt_ls() { find "${src_srt_i}" -mindepth 1; }

_srt_date_ls_lp()
{
    for i in $(_srt_date_ls)
    do
        _srt_date_mv "${i}"
    done
}

_srt_date_clean()
{
    # clean empty dirs
    if [ -z "$(_srt_ls)" ]
    then
        trash-put "${src_srt_i}"
    else
        _prn_b "warning: files still in old dir [ ${src_srt_i} ], not trashing"
    fi
}

_srt_date_x()
{
    _srt_date_ini_i "${1}"
    _srt_date_ls_lp
    _srt_date_clean
}

# srt - src root containing src dir's

_srt_date_r_ls() { _find_d_grp "${src_srt}" "${sd_srt_pattern}"; }

_srt_date_r_lp()
{
    for d in $(_srt_date_r_ls)
    do
        _srt_date_x "${d}"
    done
}

_srt_date_r()
{
    _srt_date_ini "${@}"
    _srt_date_read
    _srt_date_r_lp
}

# srt sd

_srt_sd()
{
    [ -n "${sd_dcim}" ] || _sd_ini
    _srt_date_r "${sd_dcim}"
}

# srt: size

# in progress
# - [ ] high prio - useful for segregating large files...
# complicated by keeping together unique identifiers:
# keeping all files with the same identifier together.
# IE, 'mv' is a batch process that could apply to
# x number of screenshots as well as a video.

_srt_siz_ini()
{
    dmin="${1}"
    dmax="${2}"
    src_sz="${3}"
    prfx="d${dmax}-"
}

# mv

_srt_size_ini_x()
{
  src_szx="${f}"
  dst_szx="${prfx}${base1}" 
  # todo - extract full path from $src_sz ... 
  # similar to in srt_date..
 }

_srt_siz_mv_x() { mv "${src_szx}" "${dst_szx}"; }

_srt_siz_mv()
{
    _srt_size_ini_x "${@}"
    echo "${dst_szx}"
    exit
    _srt_siz_mv_x
}

# loop

_srt_siz_ls_x()
{
    find "${src_sz}" \
        -mindepth 1 -maxdepth 1 \
        -size "+${dmin}" -size "-${dmax}" \
        -type f -exec realpath {} \; |\
        \
        grep -v jpg
}

_srt_siz_ls() { sz_ls="$(_srt_siz_ls_x)"; }

_srt_siz_test()
{
    _prn_b "src: ${srt_sz}" "dmax: ${dmax}" "dmin: ${dmin}"
    _prn_b "matched files:" "${sz_ls}"
    
    [ -d "${src_x}" ] && return
    _prn_b "no directory; exiting"
    exit 1
}

_srt_siz_confirm()
{
    printf "Rename files based on size? y/n \n"
    read -r confirm
    
    [ "${confirm}" = "y" ] && return
    printf "Exiting on -no-"
    exit 1
}

_srt_siz_lpx()
{
    while read -r f
    do
        _srt_siz_mv "${f}"
    done <<< "${sz_ls}"
}

# control

_srt_size()
{
    _srt_siz_ini "${@}"
    _srt_siz_ls
    _srt_siz_test
    _srt_sia_confirm
    _srt_siz_lpx
}

# meta sort

_srt_sz10()  { _srt_size 0M  11M  "${@}" ; }
_srt_sz60()  { _srt_size 30M 61M  "${@}" ; }
_srt_sz200() { _srt_size 60M 200M "${@}" ; }

_srt_siz_all()
{
    sort_size 0M  11M  "${1}"
    sort_size 10M 31M  "${1}"
    sort_size 30M 61M  "${1}"
    sort_size 60M 200M "${1}"
}

# sort: client profiles

_src_cl_ls()
{
    find "${src_cl_r}" \
        -mindepth 1 -maxdepth 1 -name "*${pattern_cl}\.*"
}

_mv2cl_ini()
{
    src_cl_r="${1}"
    dst_cl_r="${2}"
    pattern_cl="${3}*" # client annotation pattern
    
    dst_cl_d="$(basename "${src_cl_r}")"
    dst_cl_rx="${dst_cl_r}/${dst_cl_d}"
    src_cl_ls=$(_src_cl_ls)
    echo "src $src_cl_r"
    
    if [ -n "${src_cl_ls}" ]
    then
        mkdir -p "${dst_cl_r}"
        mkdir -p "${dst_cl_rx}"
    else
        _prn_b "nothing to move of pattern ${pattern_cl}"
        return 1
    fi
}

_mv2cl_x_ini()
{
    src_cl_i="${1}"
    dst_cl_i="${dst_cl_rx}/$(basename "${src_cl_i}")"
}

_mv2cl_x()
{
    # session(y) -> client(x)
    _mv2cl_x_ini "${1}"
    _prn_b "${src_cl_i} -> ${dst_cl_i}"
    mv "${src_cl_i}" "${dst_cl_i}"
}

_mv2cl_lp()
{
    _prn_b "moving pattern ${pattern_cl}"
    for i in ${src_cl_ls}
    do
        _mv2cl_x "${i}"
    done
}

_mv2cl()
{
    _mv2cl_ini "${@}"
    [ $? -eq 1 ] && return
    _mv2cl_lp
}

# sync

_syc_ini()
{
    r_c="${1}"
    i="${2}"
    syc_src="${r}/${i}"
    syc_dst="${r_c}/${i}"
}

_syc_x()
{
    _syc_ini "${@}"
    _prn_h "rclone sync to < ${syc_src} >"
    _rc_syc
}

_syc_g1_x () { _syc_x "${rep_g1_x}" "${1}" ; }

_syc_o1_x () { _syc_x "${rep_o1_x}" "${1}" ; }

_syc_o1_y () { _syc_x "${rep_o1_y}" "${1}" ; }

_syc_dv_b () { _syc_x "${rep_dv_b}" "${1}" ; }

_syc_22_()
{
    sfx="x22a/${2}"
    syc_src="${ry}/${sfx}"
    syc_dst="${r_c}/${sfx}"
    _prn_h "rclone sync to < ${syc_src} >"
    _rc_syc
}

# macros

_all_xa()
{
    _srt_sd "${@}"
    _sd_mvx "${@}"
}

_all_xb()
{
    _all_xa "${@}"
    _sd_bkp
}

_all_xc()
{
    _all_xb "${@}"
    _syc_o1_x
}

_all_sd()
{
    _srt_sd
    _sd_mvx "${@}"
}

_help()
{
    _prn_b "TODO"
}

_no_arg()
{
    _prn_b "arguments required"
    # todo - print simplified cli cmd help structure
}

_main()
{
    cmd="${1}" && shift 1

    _ini

    _prn_h "initialise msurf"

    case ${cmd} in
        cl|client-x)      _mv2cl      "${@}" ;;
        sd-bkp|sdbkp)     _sd_bkp     "${@}" ;;
        sd-prn|sdprn)     _sd_prn     "${@}" ;;
        sd-mv|sdmv)       _sd_mvx     "${@}" ;;
        sr|srt|sz)
            cmd_sub="${1}" && shift 1
            case ${cmd_sub} in
                size)   _srt_size     "${@}" ;;
                s10)    _srt_sz10     "${@}" ;;
                s60)    _srt_sz60     "${@}" ;;
                s200)   _srt_sz200    "${@}" ;;
                dir)    _srt_date_dir "${@}" ;; # sort arg dir
                sd)     _srt_sd ;;
            esac
            ;;
        sy|sync|syc)
            cmd_sub="${1}" && shift 1
            case ${cmd_sub} in
                y21)    _syc_year     "${@}" ;;
                dvb)    _syc_dv_b     "${@}" ;;
                g1)     _syc_g1_x     "${@}" ;;
                o1)     _syc_o1_x     "${@}" ;;
                *)      _syc_o1_x     "${@}" ;;
            esac
            ;;
        m|macro|a|al)
            cmd_sub="${1}" && shift 1
            case ${cmd_sub} in
                a)      _all_xa    "${@}"   ;;
                b)      _all_xb    "${@}"   ;;
                c)      _all_xc    "${@}"   ;;
                sd)     _all_sd    "${@}"   ;;
            esac
            ;;
        help)      _help   ;;
        *|noarg)   _no_arg ;;
    esac
}

_main "${@}"
